/** Regenerates lib/data/board-papers/index.ts from whatever JSON sets exist. */
import { readdirSync, writeFileSync, readFileSync, mkdirSync, existsSync } from "fs";
const dir = "lib/data/board-papers";
mkdirSync(dir, { recursive: true });   // a clone with no papers yet must still build
const files = readdirSync(dir).filter(f => f.endsWith(".json")).sort();

// Index any paper that transcribed properly. board.ts decides what each one
// is good for: only fully-solved sets become full mock papers, while a partly
// solved set still contributes its answered questions to drills.
const usable = files.filter(f => {
  try {
    const p = JSON.parse(readFileSync(`${dir}/${f}`, "utf8"));
    return Array.isArray(p.questions) && p.questions.length >= 30
      && p.questions.some(q => q.answer);
  } catch { return false; }
});

const lines = usable.map((f, i) => `import p${i} from "./${f}";`);
writeFileSync(`${dir}/index.ts`,
`// AUTO-GENERATED by scripts/gen-index.mjs — do not edit by hand.
${lines.join("\n")}

export const RAW_PAPERS: any[] = [${usable.map((_, i) => `p${i}`).join(", ")}];
`);
const complete = usable.filter(f => {
  const p = JSON.parse(readFileSync(`${dir}/${f}`, "utf8"));
  return p.questions.length === 38 && p.questions.every(q => q.answer);
}).length;
console.log(`indexed ${usable.length}/${files.length} papers (${complete} complete -> full mocks)`);
